'use client';

import React, { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Textarea } from "@/components/ui/textarea";
import { ComplianceScore } from "@/components/compliance-score";
import { CheckCircle2, XCircle, RotateCcw, Save, ArrowLeft, Loader2, Bot } from "lucide-react";

export default function ApprovalsPage() {
    // Mock data - in a real app this would come from a context or API
    const [selectedItem, setSelectedItem] = useState<string | null>("1");
    const [isEditing, setIsEditing] = useState(false);
    const [editContent, setEditContent] = useState("");

    const contentItems = [
        {
            id: "1",
            title: "Episode 3.1 Teaser - Twitter",
            originalContent: "Three weeks of research. Or 11 seconds. \n\nMaya asked one question. Signal Studio delivered a complete analysis—with sources, reasoning, and audit trail.\n\nThe gap between knowing and proving? It just closed.\n\n#DecisionVelocity #WealthManagement #AIForFinance",
            complianceScore: 92,
            complianceReasons: ["Good use of keywords", "Tone matches brand voice"],
            aiModel: "Claude 3.5 Sonnet"
        },
        {
            id: "2",
            title: "Episode 3.1 Teaser - LinkedIn",
            originalContent: "To the skeptics:\n\nWe know what you're thinking. \"Another AI tool?\"\n\nWatch Episode 3.1. See what happens when the 11-second answer changes everything.",
            complianceScore: 85,
            complianceReasons: ["Slightly aggressive start", "Check tone"],
            aiModel: "Gemini 1.5 Pro"
        }
    ];

    const currentItem = contentItems.find(i => i.id === selectedItem);

    const handleEdit = () => {
        setIsEditing(true);
        setEditContent(currentItem?.originalContent || "");
    };

    const handleSave = () => {
        // Save logic would go here
        setIsEditing(false);
    };

    return (
        <div className="flex bg-slate-950 h-[calc(100vh-4rem)]">
            {/* Sidebar List */}
            <div className="w-80 border-r border-border bg-card/50 p-4 overflow-y-auto">
                <h2 className="text-lg font-semibold text-foreground mb-4">Pending Review</h2>
                <div className="space-y-3">
                    {contentItems.map(item => (
                        <div
                            key={item.id}
                            onClick={() => { setSelectedItem(item.id); setIsEditing(false); }}
                            className={`p-3 rounded-lg border cursor-pointer transition-all ${selectedItem === item.id
                                ? 'bg-cyan-950/40 border-cyan-700/50 ring-1 ring-cyan-700/50'
                                : 'bg-slate-900 border-slate-800 hover:border-slate-700'
                                }`}
                        >
                            <div className="flex justify-between items-start mb-2">
                                <h3 className="text-sm font-medium text-foreground">{item.title}</h3>
                                <Badge variant="secondary" className="text-[10px] bg-secondary text-secondary-foreground">Draft</Badge>
                            </div>
                            <p className="text-xs text-muted-foreground line-clamp-2">{item.originalContent}</p>
                            <div className="mt-2 flex items-center justify-between">
                                <span className="text-[10px] text-slate-600 flex items-center">
                                    <Bot className="w-3 h-3 mr-1" /> {item.aiModel}
                                </span>
                                <div className={`w-2 h-2 rounded-full ${item.complianceScore > 90 ? 'bg-green-500' : 'bg-yellow-500'}`} />
                            </div>
                        </div>
                    ))}
                </div>
            </div>

            {/* Main Review Area */}
            <div className="flex-1 p-6 overflow-y-auto">
                {currentItem ? (
                    <div className="max-w-4xl mx-auto space-y-6">
                        {/* Header Actions */}
                        <div className="flex items-center justify-between">
                            <div>
                                <h1 className="text-2xl font-bold text-slate-100">{currentItem.title}</h1>
                                <p className="text-sm text-slate-500 flex items-center mt-1">
                                    Generated by {currentItem.aiModel} • <span className="text-xs bg-slate-800 px-2 py-0.5 rounded ml-2">v1.2</span>
                                </p>
                            </div>
                        </div>

                        {/* Main Content Grid */}
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                            {/* Left: Content Editor/Viewer */}
                            <Card className="bg-card border-border md:h-[500px] flex flex-col shadow-lg">
                                <CardHeader className="bg-card border-b border-border pb-3">
                                    <CardTitle className="text-sm font-medium text-muted-foreground flex justify-between items-center">
                                        Content
                                        {!isEditing && (
                                            <Button variant="ghost" size="sm" onClick={handleEdit} className="h-6 text-xs text-cyan-400 hover:text-cyan-300 hover:bg-cyan-950/30">
                                                Isolate & Edit
                                            </Button>
                                        )}
                                    </CardTitle>
                                </CardHeader>
                                <CardContent className="flex-1 p-4">
                                    {isEditing ? (
                                        <Textarea
                                            value={editContent}
                                            onChange={(e) => setEditContent(e.target.value)}
                                            className="h-full bg-slate-950 border-slate-700 text-slate-100 font-mono text-sm resize-none focus-visible:ring-cyan-500/50"
                                        />
                                    ) : (
                                        <div className="h-full whitespace-pre-wrap text-card-foreground text-sm font-mono leading-relaxed p-2">
                                            {currentItem.originalContent}
                                        </div>
                                    )}
                                </CardContent>
                            </Card>

                            {/* Right: Analysis & Controls */}
                            <div className="space-y-6">
                                {/* Compliance Card */}
                                <Card className="bg-card border-border shadow-md">
                                    <CardHeader className="pb-2">
                                        <CardTitle className="text-sm font-medium text-slate-400">Brand Intelligence</CardTitle>
                                    </CardHeader>
                                    <CardContent className="space-y-4">
                                        <div className="flex items-center justify-between p-3 bg-slate-950/50 rounded-lg border border-border">
                                            <span className="text-sm text-muted-foreground">Compliance Score</span>
                                            <ComplianceScore score={currentItem.complianceScore} reasons={currentItem.complianceReasons} />
                                        </div>
                                        <div className="space-y-2">
                                            <p className="text-xs font-semibold text-slate-500 uppercase tracking-wider">Analysis</p>
                                            <ul className="space-y-2">
                                                {currentItem.complianceReasons.map((r, i) => (
                                                    <li key={i} className="text-xs text-slate-400 flex items-start">
                                                        <div className="w-1.5 h-1.5 rounded-full bg-cyan-500 mt-1 mr-2 shrink-0" />
                                                        {r}
                                                    </li>
                                                ))}
                                            </ul>
                                        </div>
                                    </CardContent>
                                </Card>

                                {/* Action Buttons */}
                                <div className="grid grid-cols-1 gap-3">
                                    {isEditing ? (
                                        <div className="flex space-x-2">
                                            <Button variant="outline" className="flex-1 border-slate-700 hover:bg-white/5" onClick={() => setIsEditing(false)}>Cancel</Button>
                                            <Button className="flex-1 bg-cyan-600 hover:bg-cyan-700 text-white" onClick={handleSave}>
                                                <Save className="w-4 h-4 mr-2" /> Save Changes
                                            </Button>
                                        </div>
                                    ) : (
                                        <>
                                            <Button className="w-full bg-green-600 hover:bg-green-700 text-white shadow-lg shadow-green-900/20">
                                                <CheckCircle2 className="w-4 h-4 mr-2" /> Approve Content
                                            </Button>
                                            <div className="flex space-x-2">
                                                <Button variant="outline" className="flex-1 bg-slate-900 border-slate-700 hover:bg-red-950/30 hover:text-red-400 hover:border-red-900/50 transition-colors">
                                                    <XCircle className="w-4 h-4 mr-2" /> Reject
                                                </Button>
                                                <Button variant="outline" className="flex-1 bg-slate-900 border-slate-700 hover:bg-slate-800">
                                                    <RotateCcw className="w-4 h-4 mr-2" /> Regenerate
                                                </Button>
                                            </div>
                                        </>
                                    )}
                                </div>
                            </div>
                        </div>
                    </div>
                ) : (
                    <div className="h-full flex flex-col items-center justify-center text-slate-500">
                        <Loader2 className="w-8 h-8 animate-spin mb-4 opacity-50" />
                        <p>Select an item to review</p>
                    </div>
                )}
            </div>
        </div>
    );
}
